script to enable transfering file to a server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -25,4 +25,12 @@ ssh_options="-o StrictHostKeyChecking=no"
 # $username@$ip specifies the user and IP of the remote server we want to transfer the file to
 # :~ specifies the user's home directory on the remote server
 
-scp -i "$ssh_key" $ssh_options "$file_path" "$username@$ip":~
+scp -i "$ssh_key" $ssh_options "$file_path" "$username@$ip:~/"
+
+# checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+	echo "FILE WAS TRANSFERED SUCCESSFULLY"
+else
+	echo "FILE TRANSFER FAILED"
+fi
